import uuid
from django.db import models
from django.conf import settings
from django.utils import timezone

class AgenticWorkflow(models.Model):
    """
    Stores a React Flow graph and its metadata.
    Can be a system-level template/challenge, or a student-created flow.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, help_text="Name of the flow or challenge.")
    description = models.TextField(blank=True)
    
    # Stores the React Flow serialized state: {"nodes": [...], "edges": [...]}
    flow_data = models.JSONField(default=dict, help_text="React Flow JSON representation.")
    
    # Ownership and Template Logic
    is_template = models.BooleanField(
        default=False, 
        help_text="If True, this is a predefined challenge or example flow. If False, it belongs to a student."
    )
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='agentic_workflows',
        null=True,
        blank=True,
        help_text="Null if this is a system template."
    )

    # Optional tie-in to your existing scenarios/challenges
    scenario = models.ForeignKey(
        'scenarios.Scenario', 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        related_name='agentic_workflows',
        help_text="Optional link to a curriculum scenario."
    )
    
    # "Leave it to AI" Mode tracking
    generated_by_ai = models.BooleanField(
        default=False, 
        help_text="True if this flow was generated by the LLM in 'Leave it to AI' mode."
    )
    ai_prompt = models.TextField(
        blank=True, 
        help_text="The prompt the student used to generate this flow, if applicable."
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Agentic Workflow'
        verbose_name_plural = 'Agentic Workflows'

    def __str__(self):
        owner = "Template" if self.is_template else f"Student: {self.student.name if self.student else 'Unknown'}"
        return f"[{owner}] {self.name}"

class UserQuota(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='agentic_quota'
    )
    daily_points = models.IntegerField(default=100)
    last_reset_date = models.DateField(default=timezone.now)

    def reset_if_needed(self):
        today = timezone.now().date()
        if self.last_reset_date < today:
            self.daily_points = 100
            self.last_reset_date = today
            self.save()

    def deduct(self, amount):
        self.reset_if_needed()
        if self.daily_points >= amount:
            self.daily_points -= amount
            self.save()
            return True
        return False
        
    def __str__(self):
        return f"{self.user.username} - {self.daily_points} points"
