# Generated by Django 5.2.15 on 2026-06-24 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenticWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the flow or challenge.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('flow_data', models.JSONField(default=dict, help_text='React Flow JSON representation.')),
                ('is_template', models.BooleanField(default=False, help_text='If True, this is a predefined challenge or example flow. If False, it belongs to a student.')),
                ('generated_by_ai', models.BooleanField(default=False, help_text="True if this flow was generated by the LLM in 'Leave it to AI' mode.")),
                ('ai_prompt', models.TextField(blank=True, help_text='The prompt the student used to generate this flow, if applicable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(blank=True, help_text='Optional link to a curriculum scenario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentic_workflows', to='scenarios.scenario')),
                ('student', models.ForeignKey(blank=True, help_text='Null if this is a system template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentic_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agentic Workflow',
                'verbose_name_plural': 'Agentic Workflows',
                'ordering': ['-created_at'],
            },
        ),
    ]
