# Generated by Django 5.2.15 on 2026-06-25 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datavariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datavariant',
            name='data_payload',
            field=models.TextField(blank=True, help_text='JSON string of processed data or Base64 string for images', null=True),
        ),
        migrations.AddField(
            model_name='datavariant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_variants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='datavariant',
            unique_together={('scenario', 'name', 'user')},
        ),
    ]
