# Generated by Django 5.2.15 on 2026-06-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regression', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regressionexperiment',
            name='model_b64',
            field=models.TextField(blank=True),
        ),
    ]
